DROP TABLE IF EXISTS PatientAssignedBed;

DROP TABLE IF EXISTS Bed;

DROP TABLE IF EXISTS MedicalRecord;

DROP TABLE IF EXISTS BillingRecord;

DROP TABLE IF EXISTS BillingAccount;

DROP TABLE IF EXISTS Patient;

DROP TABLE IF EXISTS NurseAssignedWard;

DROP TABLE IF EXISTS Doctor;

DROP TABLE IF EXISTS Staff;

DROP TABLE IF EXISTS Ward;

DROP TABLE IF EXISTS WardType;